version: "3"
services:
  database:
    container_name: $PROJECT_NAME-database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DB
    restart: unless-stopped

  cache:
    container_name: $PROJECT_NAME-cache
    image: redis:6
    networks:
      - directus
    restart: unless-stopped

  directus:
    container_name: $PROJECT_NAME-directus
    image: directus/directus:latest
    ports:
      - $DIRECTUS_PORT:$DIRECTUS_PORT
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
      - external
    depends_on:
      - cache
      - database
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      PORT: $DIRECTUS_PORT

      KEY: $KEY
      SECRET: $SECRET

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: $DB_DB
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://cache:6379"

      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD

      PUBLIC_URL: $PUBLIC_URL
      CORS_ENABLED: "true"
      CORS_ORIGIN: $CORS_ORIGIN

      EXTENSIONS_AUTO_RELOAD: "true"

networks:
  directus:
    name: $INTERNAL_NETWORK_NAME
  external:
    name: $EXTERNAL_NETWORK_NAME
    external: true
